const AGENT_SARAH = {
  name: 'Sarah Hargrove',
  title: 'Team Lead · Listing Specialist',
  phone: '(713) 555-0182',
  email: 'sarah@hargrovegroup.com',
  photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
  license: 'TX Lic# 0624531',
}

const AGENT_MICHAEL = {
  name: 'Michael Hargrove',
  title: "Co-Founder · Buyer's Specialist",
  phone: '(713) 555-0183',
  email: 'michael@hargrovegroup.com',
  photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
  license: 'TX Lic# 0618742',
}

const AGENT_JESSICA = {
  name: 'Jessica Chen',
  title: "Senior Buyer's Agent · Relocation Specialist",
  phone: '(713) 555-0184',
  email: 'jessica@hargrovegroup.com',
  photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80',
  license: 'TX Lic# 0703819',
}

export const SOLD_PROPERTIES = [
  {
    slug: '3412-roseland-st',
    address: '3412 Roseland St',
    neighborhood: 'The Heights',
    city: 'Houston, TX 77008',
    salePrice: '$875,000',
    listPrice: '$875,000',
    beds: 4,
    baths: 3,
    sqft: '3,240',
    lotSize: '5,500 sf',
    yearBuilt: 2018,
    type: 'Single Family',
    status: 'Sold',
    soldDate: 'March 2025',
    daysOnMarket: 8,
    role: 'Represented Seller',
    overAsk: true,
    description: [
      'A stunning 2018-built Heights home just two blocks from the 19th Street corridor. Four bedrooms, three full baths, and an open-concept main floor make this one of the most livable homes in the Inner Loop. The chef\'s kitchen features quartz counters, a 48-inch range, and custom cabinetry that flows into a generous dining and living area.',
      'The primary suite is a true retreat — vaulted ceilings, a spa bath with soaking tub and walk-in shower, and a large custom closet. The private backyard with covered patio and low-maintenance turf is ideal for entertaining. This home sold in 8 days with multiple offers, above list price.',
    ],
    features: [
      '48-inch gas range in chef\'s kitchen',
      'Quartz countertops throughout',
      'Vaulted ceiling in primary suite',
      'Custom closet with island',
      'Covered patio with outdoor speakers',
      'Low-maintenance turf backyard',
      'Two-car attached garage',
      'Walking distance to 19th Street',
    ],
    amenities: [
      'Dedicated home study',
      'Mudroom with built-ins',
      'Second-floor laundry room',
      'Sprinkler system',
      'Full security system',
      'Smart thermostat',
    ],
    photos: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: AGENT_SARAH,
  },
  {
    slug: '1827-kirby-dr-1402',
    address: '1827 Kirby Dr, #1402',
    neighborhood: 'River Oaks',
    city: 'Houston, TX 77019',
    salePrice: '$1,250,000',
    listPrice: '$1,250,000',
    beds: 3,
    baths: 3,
    sqft: '2,890',
    lotSize: 'N/A (Condo)',
    yearBuilt: 2015,
    type: 'Condo',
    status: 'Sold',
    soldDate: 'February 2025',
    daysOnMarket: 14,
    role: 'Represented Buyer',
    overAsk: false,
    description: [
      'A sophisticated 14th-floor residence at 1827 Kirby — one of River Oaks\' most coveted luxury mid-rises. Three bedrooms, three full baths, and panoramic views of the Houston skyline and tree canopy from every room. Refined finishes include wide-plank hardwood floors, Venetian plaster accent walls, and a custom kitchen by Copeland.',
      'The primary suite features two walk-in closets, a spa bath with heated floors and a soaking tub, and direct access to a private terrace. Building amenities include a 24-hour concierge, resort-style pool, fitness center, and two valet parking spaces. Our buyer secured this unit at list price in a competitive spring market.',
    ],
    features: [
      'Panoramic skyline and tree-canopy views',
      'Wide-plank hardwood floors throughout',
      'Custom Copeland kitchen cabinetry',
      'Heated bathroom floors in primary suite',
      'Private balcony with city views',
      'Two valet parking spaces included',
      'Climate-controlled storage unit',
      'Floor-to-ceiling windows',
    ],
    amenities: [
      '24-hour concierge',
      'Resort-style rooftop pool',
      'Fitness center and yoga studio',
      'Valet parking',
      'Private dining room',
      'Pet-friendly with dog park',
    ],
    photos: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
    ],
    agent: AGENT_MICHAEL,
  },
  {
    slug: '526-w-24th-st',
    address: '526 W 24th St',
    neighborhood: 'The Heights',
    city: 'Houston, TX 77008',
    salePrice: '$695,000',
    listPrice: '$680,000',
    beds: 3,
    baths: 2,
    sqft: '2,140',
    lotSize: '4,400 sf',
    yearBuilt: 2016,
    type: 'Single Family',
    status: 'Sold',
    soldDate: 'January 2025',
    daysOnMarket: 5,
    role: 'Represented Seller',
    overAsk: true,
    description: [
      'A beautifully maintained 2016 Heights bungalow-style home with three bedrooms, two full baths, and an open main floor designed for everyday living. The kitchen anchors the space with a large quartz island, stainless appliances, and custom open shelving that leads into a comfortable living area with hardwood floors and abundant natural light.',
      'Listed at $680,000 and sold in 5 days with multiple offers at $695,000 — a testament to the team\'s pricing strategy and pre-market exposure. The backyard features a pergola, raised garden beds, and a two-car detached garage accessed from the rear alley.',
    ],
    features: [
      'Large quartz kitchen island',
      'Hardwood floors throughout main level',
      'Pergola and landscaped backyard',
      'Raised garden beds',
      'Detached two-car garage (alley access)',
      'Covered front porch',
      'Recessed lighting throughout',
      'Energy-efficient windows',
    ],
    amenities: [
      'Covered front porch',
      'Backyard pergola',
      'Raised garden beds',
      'Utility room with storage',
      'Sprinkler system',
      'Ring security system',
    ],
    photos: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: AGENT_SARAH,
  },
  {
    slug: '14-briar-hollow-ln',
    address: '14 Briar Hollow Ln',
    neighborhood: 'Tanglewood',
    city: 'Houston, TX 77027',
    salePrice: '$2,100,000',
    listPrice: '$2,195,000',
    beds: 5,
    baths: 5,
    sqft: '5,600',
    lotSize: '12,000 sf',
    yearBuilt: 2014,
    type: 'Single Family',
    status: 'Sold',
    soldDate: 'December 2024',
    daysOnMarket: 22,
    role: 'Represented Seller',
    overAsk: false,
    description: [
      'An exceptional Tanglewood estate offering five bedrooms, five baths, a resort-style backyard, and a four-car garage on a 12,000 sf lot. Built in 2014 with premium materials throughout, the home features a dramatic two-story entry, formal living and dining rooms, a gourmet kitchen with La Cornue range, and a glass-walled family room that opens to the outdoor living pavilion.',
      'The backyard is designed for year-round entertaining — a sparkling pool and spa, full outdoor kitchen, and a covered pavilion with motorized screens and a fireplace. The primary suite occupies its own wing with a sitting room, dual closets, and a spa bath with heated floors and a steam shower.',
    ],
    features: [
      'Resort-style pool and spa',
      'Full outdoor kitchen with motorized screened pavilion',
      'La Cornue range in gourmet kitchen',
      'Two-story entry with custom iron staircase',
      'Wine room (400+ bottles)',
      'Home theater with tiered seating',
      'Four-car garage with epoxy floors',
      'Crestron whole-home automation',
    ],
    amenities: [
      'Home theater',
      'Wine room',
      'Exercise room',
      'Game room / flex space',
      'Formal study with custom built-ins',
      'Second-floor laundry room',
    ],
    photos: [
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: AGENT_SARAH,
  },
  {
    slug: '2209-dunlavy-st',
    address: '2209 Dunlavy St',
    neighborhood: 'Montrose',
    city: 'Houston, TX 77006',
    salePrice: '$560,000',
    listPrice: '$560,000',
    beds: 3,
    baths: 2,
    sqft: '1,980',
    lotSize: '3,200 sf',
    yearBuilt: 2019,
    type: 'Townhome',
    status: 'Sold',
    soldDate: 'December 2024',
    daysOnMarket: 11,
    role: 'Represented Buyer',
    overAsk: false,
    description: [
      'A sleek 2019-built Montrose townhome steps from the Menil Collection and Westheimer dining corridor. Three bedrooms, two full baths, a private rooftop terrace, and an attached two-car garage — a rare combination in Montrose. The open main level features 10-foot ceilings, wide-plank floors, and a kitchen with a quartz waterfall island and KitchenAid appliances.',
      'Our buyer identified this property before it hit the market through the team\'s off-market network, allowing them to negotiate directly and close at list price without a bidding war. The third-floor primary suite features a spa bath and direct access to the rooftop deck.',
    ],
    features: [
      'Private rooftop terrace',
      'Wide-plank hardwood floors',
      'Quartz waterfall kitchen island',
      'KitchenAid appliance package',
      '10-foot ceilings on main level',
      'Attached two-car garage',
      'Pre-wired for EV charger',
      'Walking distance to Menil Collection',
    ],
    amenities: [
      'Rooftop terrace',
      'Private 2-car garage',
      'Custom closet system',
      'Tankless water heater',
      'Nest thermostat',
      'Ring doorbell',
    ],
    photos: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: AGENT_JESSICA,
  },
  {
    slug: '9802-emerald-glen-dr',
    address: '9802 Emerald Glen Dr',
    neighborhood: 'Sugar Land',
    city: 'Sugar Land, TX 77498',
    salePrice: '$745,000',
    listPrice: '$729,000',
    beds: 4,
    baths: 3,
    sqft: '3,810',
    lotSize: '8,200 sf',
    yearBuilt: 2017,
    type: 'Single Family',
    status: 'Sold',
    soldDate: 'November 2024',
    daysOnMarket: 7,
    role: 'Represented Seller',
    overAsk: true,
    description: [
      'A meticulously maintained Sugar Land home in the sought-after Riverstone community, zoned to Fort Bend ISD. Four bedrooms, three full baths, a three-car garage, and a backyard pool make this one of the most complete homes in its price range. The open-concept main floor features a gourmet kitchen with double ovens and a large island that flows into the family room.',
      'Listed at $729,000, the home received six offers in its first weekend and closed at $745,000 — $16,000 over list price. The strategy included professional staging, a pre-listing home inspection, and a targeted digital campaign to relocating buyers in the Energy Corridor.',
    ],
    features: [
      'Pool and spa with waterfall feature',
      'Three-car garage',
      'Gourmet kitchen with double ovens',
      'Oversized kitchen island',
      'Primary suite with sitting area',
      'Covered outdoor living area',
      'Dedicated home office',
      'Zoned to Fort Bend ISD',
    ],
    amenities: [
      'Swimming pool and spa',
      'Covered patio',
      'Home office / study',
      'Formal dining room',
      'Utility room with built-ins',
      'HOA community amenities',
    ],
    photos: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&q=80',
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: AGENT_SARAH,
  },
  {
    slug: '4430-merwin-st',
    address: '4430 Merwin St',
    neighborhood: 'Upper Kirby',
    city: 'Houston, TX 77098',
    salePrice: '$980,000',
    listPrice: '$965,000',
    beds: 4,
    baths: 4,
    sqft: '3,520',
    lotSize: '4,800 sf',
    yearBuilt: 2020,
    type: 'Single Family',
    status: 'Sold',
    soldDate: 'November 2024',
    daysOnMarket: 9,
    role: 'Represented Seller',
    overAsk: true,
    description: [
      'A beautifully executed 2020 Upper Kirby home with four bedrooms, four full baths, and a thoughtful layout that maximizes every square foot. Located in one of the most walkable Inner Loop corridors, this home is steps from Kirby restaurants, Whole Foods, and Buffalo Bayou Park. The main level features an open-plan kitchen and living area with 11-foot ceilings and sliding glass doors to the backyard.',
      'The primary suite features a large walk-in closet with custom millwork, a spa bath with a soaking tub and dual rainfall showers, and a private balcony. Sold above list price in 9 days with three competing offers — our seller netted the best terms through the team\'s negotiation strategy.',
    ],
    features: [
      'Soaking tub and dual rainfall showers in primary bath',
      'Private primary balcony',
      '11-foot ceilings on main level',
      'Sliding glass doors to backyard',
      'Custom millwork throughout',
      'Chef\'s kitchen with 48-inch range',
      'Two-car attached garage',
      'Walking distance to Buffalo Bayou Park',
    ],
    amenities: [
      'Private balcony off primary suite',
      'Covered rear patio',
      'Two-car garage with storage',
      'Laundry room on second floor',
      'Home study / office',
      'Smart home features',
    ],
    photos: [
      'https://images.unsplash.com/photo-1598228723793-52759bba239c?w=1200&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: AGENT_SARAH,
  },
  {
    slug: '17-grand-regency-cir',
    address: '17 Grand Regency Cir',
    neighborhood: 'The Woodlands',
    city: 'The Woodlands, TX 77382',
    salePrice: '$1,495,000',
    listPrice: '$1,525,000',
    beds: 5,
    baths: 5,
    sqft: '4,930',
    lotSize: '11,500 sf',
    yearBuilt: 2016,
    type: 'Single Family',
    status: 'Sold',
    soldDate: 'October 2024',
    daysOnMarket: 18,
    role: 'Represented Buyer',
    overAsk: false,
    description: [
      'A grand Woodlands estate in the prestigious Carlton Woods enclave — a guard-gated community with a Jack Nicklaus Signature Golf Course and world-class amenities. Five bedrooms, five full baths, a three-car garage, and a resort-style backyard on an 11,500 sf lot backing to a greenbelt. The home features soaring ceilings, a professional kitchen, and a first-floor primary suite.',
      'Our buyer relocated from Chicago and needed to close in 45 days. The team coordinated the inspection, appraisal, and title simultaneously while negotiating $30,000 off list price. The buyer is zoned to Conroe ISD\'s highly ranked College Park High School.',
    ],
    features: [
      'Resort-style pool with grotto and slide',
      'First-floor primary suite',
      'Professional kitchen with Sub-Zero refrigerator',
      'Soaring two-story entry',
      'Three-car garage',
      'Greenbelt lot — no rear neighbors',
      'Home theater',
      'Zoned to Conroe ISD (College Park HS)',
    ],
    amenities: [
      'Home theater',
      'Game room',
      'Exercise room',
      'Formal study',
      'Three-car garage',
      'HOA — Carlton Woods guard gate and golf access',
    ],
    photos: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: AGENT_MICHAEL,
  },
  {
    slug: '6118-chevy-chase-dr',
    address: '6118 Chevy Chase Dr',
    neighborhood: 'Memorial',
    city: 'Houston, TX 77024',
    salePrice: '$1,150,000',
    listPrice: '$1,175,000',
    beds: 4,
    baths: 4,
    sqft: '4,200',
    lotSize: '9,800 sf',
    yearBuilt: 2012,
    type: 'Single Family',
    status: 'Sold',
    soldDate: 'October 2024',
    daysOnMarket: 13,
    role: 'Represented Seller',
    overAsk: false,
    description: [
      'A graceful Memorial home on a quiet street in Spring Branch ISD, offering four bedrooms, four full baths, a study, game room, and a beautiful backyard with a pool and spa. Built in 2012 with traditional architecture and premium finishes throughout — hardwood floors, beadboard ceilings, and custom millwork give the home a classic quality that newer construction rarely achieves.',
      'The team worked with the seller over three months prior to listing — advising on strategic updates, coordinating staging, and building a pre-market buyer list. The home sold in 13 days, giving the seller time to finalize their purchase in The Woodlands without a contingency.',
    ],
    features: [
      'Pool and spa with flagstone surround',
      'Hardwood floors throughout main level',
      'Beadboard ceilings and custom millwork',
      'Chef\'s kitchen with double ovens',
      'Covered back porch with outdoor fireplace',
      'Three-car garage',
      'Zoned to Spring Branch ISD',
      'Study and second-floor game room',
    ],
    amenities: [
      'Swimming pool and spa',
      'Outdoor fireplace',
      'Home study',
      'Second-floor game room',
      'Three-car garage',
      'Sprinkler and landscape lighting',
    ],
    photos: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: AGENT_SARAH,
  },
]
