export const TEAM_MEMBERS = [
  {
    name: 'Sarah Hargrove',
    title: 'Team Lead',
    license: 'TX Lic# 0624531',
    phone: '(713) 555-0182',
    email: 'sarah@hargrovegroup.com',
    address: '3200 SW Freeway Ste 2400, Houston, TX 77027',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80',
    social: {
      instagram: '#',
      facebook: '#',
      linkedin: '#',
      youtube: '#',
    },
    bio: [
      "Sarah Hargrove founded the Hargrove Group after a decade as a top-producing solo agent in Houston's Inner Loop. Her specialization in listing strategy, staging consultation, and seller representation has helped over 300 Houston homeowners achieve record sale prices.",
      "A former interior designer, Sarah brings an eye for presentation that most agents simply can't match. She understands how buyers think and positions every property to speak to the right audience — resulting in faster sales and higher net proceeds for her sellers.",
      'Sarah serves the Heights, Montrose, Midtown, River Oaks, and Upper Kirby neighborhoods and is recognized annually as a top 1% producer by the Houston Association of REALTORS®.',
    ],
    specialties: ['Listing Strategy', 'Home Staging', 'Inner Loop', 'Luxury Homes', 'Pricing Analysis'],
    credentials: [
      'Certified Luxury Home Marketing Specialist (CLHMS)',
      'Accredited Seller Representative (ASR)',
      'Houston Association of REALTORS® Member',
      'Texas Association of REALTORS® Member',
      'National Association of REALTORS® Member',
    ],
    stats: [
      { value: '300+', label: 'Homes Sold' },
      { value: '$180M+', label: 'Total Volume' },
      { value: '12', label: 'Years in Houston' },
    ],
  },
  {
    name: 'Michael Hargrove',
    title: 'Co-Founder',
    license: 'TX Lic# 0618742',
    phone: '(713) 555-0183',
    email: 'michael@hargrovegroup.com',
    address: '3200 SW Freeway Ste 2400, Houston, TX 77027',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
    social: {
      instagram: '#',
      facebook: '#',
      linkedin: '#',
      youtube: '#',
    },
    bio: [
      "Michael Hargrove's background in real estate investment gives every buyer he represents a measurable advantage at the negotiating table. Before co-founding the Hargrove Group, he spent five years as a licensed real estate investor, acquiring and repositioning properties across Houston's emerging neighborhoods.",
      "He brings that investor mindset to every buyer transaction — evaluating a home not just as a place to live, but as a long-term financial asset. Whether you're buying your first home or your fifth investment property, Michael helps you think about what the numbers mean.",
      'Michael specializes in Memorial, Tanglewood, West University Place, and Bellaire. He has helped over 450 Houston buyers close successfully, including dozens of relocating professionals and corporate transferees.',
    ],
    specialties: ["Buyer's Representation", 'Investment Properties', 'Relocation', 'Negotiation', 'West Houston'],
    credentials: [
      "Accredited Buyer's Representative (ABR)",
      'Certified Residential Investment Specialist',
      'Houston Association of REALTORS® Member',
      'Texas Association of REALTORS® Member',
    ],
    stats: [
      { value: '450+', label: 'Buyers Represented' },
      { value: '$140M+', label: 'Buyer Volume' },
      { value: '11', label: 'Years of Experience' },
    ],
  },
  {
    name: 'Jessica Chen',
    title: "Senior Buyer's Agent",
    license: 'TX Lic# 0703819',
    phone: '(713) 555-0184',
    email: 'jessica@hargrovegroup.com',
    address: '3200 SW Freeway Ste 2400, Houston, TX 77027',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&q=80',
    social: {
      instagram: '#',
      facebook: '#',
      linkedin: '#',
    },
    bio: [
      "Jessica Chen joined the Hargrove Group after earning her license and quickly became the team's go-to specialist for Houston's thriving suburban communities. She has an unmatched knowledge of Sugar Land, Katy, Pearland, and The Woodlands — markets where master-planned communities, new construction, and excellent school districts drive strong buyer demand.",
      'A certified Relocation Specialist, Jessica has guided dozens of families from out of state through the Houston buying process entirely remotely — using virtual tours, video walkthroughs, and detailed written analyses to help buyers make confident decisions from anywhere.',
      'Her calm, methodical approach and deep community knowledge make her an exceptional resource for buyers who are unfamiliar with Houston and need a trusted local expert to guide them.',
    ],
    specialties: ['Sugar Land', 'The Woodlands', 'Katy', 'Relocation', 'New Construction'],
    credentials: [
      'Certified Relocation Specialist (CRS)',
      'New Construction Specialist',
      'Houston Association of REALTORS® Member',
      'Texas Association of REALTORS® Member',
    ],
    stats: [
      { value: '180+', label: 'Buyers Helped' },
      { value: '48', label: 'Relocation Clients' },
      { value: '6', label: 'Years in Real Estate' },
    ],
  },
  {
    name: 'Carlos Rivera',
    title: 'Operations Manager',
    license: 'TX Lic# 0715203',
    phone: '(713) 555-0185',
    email: 'carlos@hargrovegroup.com',
    address: '3200 SW Freeway Ste 2400, Houston, TX 77027',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&q=80',
    social: {
      instagram: '#',
      facebook: '#',
      linkedin: '#',
    },
    bio: [
      'Carlos Rivera manages every transaction the Hargrove Group handles from contract to close. With a background in title operations and escrow, he brings a rare level of expertise to the behind-the-scenes work that determines whether a deal closes smoothly or falls apart.',
      'Carlos coordinates with lenders, title companies, inspectors, and attorneys to keep every file on track. He monitors contingency deadlines, prepares closing disclosures, and serves as the primary point of contact for all parties throughout the transaction period.',
      "Thanks to Carlos, the Hargrove Group's clients consistently close on time and without last-minute surprises — an outcome that requires diligence, attention to detail, and deep relationships with Houston's top closing professionals.",
    ],
    specialties: ['Transaction Management', 'Contract-to-Close', 'Title & Escrow', 'Client Communication'],
    credentials: [
      'Licensed Texas Real Estate Agent',
      'Certified Transaction Coordinator',
      'Houston Association of REALTORS® Member',
    ],
    stats: [
      { value: '600+', label: 'Transactions Managed' },
      { value: '98%', label: 'On-Time Close Rate' },
      { value: '7', label: 'Years in Real Estate' },
    ],
  },
]
