export const FEATURED_LISTINGS = [
  {
    slug: '2814-wroxton-rd',
    address: '2814 Wroxton Rd',
    neighborhood: 'West University Place',
    city: 'Houston, TX 77005',
    listPrice: '$1,395,000',
    beds: 4,
    baths: 4,
    sqft: '3,980',
    lotSize: '6,200 sf',
    yearBuilt: 2019,
    type: 'Single Family',
    status: 'For Sale',
    description: [
      'An exceptional West U home built in 2019, offering four bedrooms, four full baths, and a thoughtfully designed open floor plan across nearly 4,000 square feet. The first floor features a formal study, chef\'s kitchen with Thermador appliances, butler\'s pantry, and a spacious living room that opens to a covered outdoor patio.',
      'The primary suite occupies the entire second-floor rear, with dual walk-in closets, a spa bath with soaking tub and frameless glass shower, and a private balcony overlooking the backyard. Three additional bedrooms, two baths, and a large game room complete the upper level.',
    ],
    features: [
      'Chef\'s kitchen with Thermador appliances',
      'Hardwood floors throughout first floor',
      'Primary suite with spa bath and private balcony',
      'Covered outdoor patio with summer kitchen',
      'Three-car garage with epoxy floors',
      'Smart home system (lighting, security, HVAC)',
      'Tankless water heaters',
      'Zoned to West U Elementary',
    ],
    amenities: [
      'Game room',
      'Formal study / home office',
      'Butler\'s pantry',
      'Mud room with built-ins',
      'Laundry room on second floor',
      'Sprinkler system',
    ],
    photos: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: {
      name: 'Sarah Hargrove',
      title: 'Team Lead · Listing Specialist',
      phone: '(713) 555-0182',
      email: 'sarah@hargrovegroup.com',
      photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
      license: 'TX Lic# 0624531',
    },
    coordinates: { lat: 29.7152, lng: -95.4300 },
  },
  {
    slug: '408-avondale-st',
    address: '408 Avondale St',
    neighborhood: 'Montrose',
    city: 'Houston, TX 77006',
    listPrice: '$725,000',
    beds: 3,
    baths: 3,
    sqft: '2,310',
    lotSize: '2,100 sf',
    yearBuilt: 2021,
    type: 'Townhome',
    status: 'Pending',
    description: [
      'A sleek 2021-built Montrose townhome offering three bedrooms, three full baths, and a rooftop terrace with downtown Houston views. The main living level features 10-foot ceilings, wide-plank white oak floors, and an open-plan kitchen and living area with floor-to-ceiling windows.',
      'The kitchen is appointed with quartz waterfall counters, custom cabinetry to the ceiling, a 36-inch gas range, and an oversized island that seats four. The primary suite offers a walk-in closet with custom shelving and an en-suite bath with double vanity and frameless shower.',
    ],
    features: [
      'Rooftop terrace with downtown Houston views',
      'Wide-plank white oak hardwood floors',
      'Quartz waterfall kitchen counters',
      '36-inch gas range',
      'Floor-to-ceiling windows on main level',
      '10-foot ceilings throughout',
      'Private two-car garage',
      'Pre-wired for EV charger',
    ],
    amenities: [
      'Rooftop terrace',
      'Private garage (2-car)',
      'Custom closet systems',
      'Tankless water heater',
      'Nest thermostat',
      'Ring doorbell system',
    ],
    photos: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: {
      name: 'Sarah Hargrove',
      title: 'Team Lead · Listing Specialist',
      phone: '(713) 555-0182',
      email: 'sarah@hargrovegroup.com',
      photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
      license: 'TX Lic# 0624531',
    },
    coordinates: { lat: 29.7474, lng: -95.3901 },
  },
  {
    slug: '1011-tulane-st',
    address: '1011 Tulane St',
    neighborhood: 'The Heights',
    city: 'Houston, TX 77008',
    listPrice: '$849,000',
    beds: 4,
    baths: 3,
    sqft: '2,870',
    lotSize: '5,000 sf',
    yearBuilt: 2017,
    type: 'Single Family',
    status: 'For Sale',
    description: [
      'A beautifully crafted 2017 Heights home on a full 5,000 sf lot, just two blocks from 19th Street. Four bedrooms, three full baths, a dedicated study, and a backyard oasis with a pool make this a rare find in one of Houston\'s most walkable neighborhoods.',
      'The chef\'s kitchen opens to a bright family room with custom built-ins and a gas fireplace. The primary suite features a vaulted ceiling, dual vanities, soaking tub, and a walk-in closet with an island. The backyard pool and spa are surrounded by travertine decking and a full summer kitchen.',
    ],
    features: [
      'Pool and spa with travertine decking',
      'Summer kitchen in backyard',
      'Gas fireplace with custom built-ins',
      'Vaulted ceiling in primary suite',
      'Chef\'s kitchen with gas range',
      'Dedicated home study with French doors',
      'Two-car attached garage',
      'Walking distance to 19th Street',
    ],
    amenities: [
      'Swimming pool and spa',
      'Outdoor summer kitchen',
      'Home study / office',
      'Custom built-in shelving',
      'Sprinkler and landscape lighting',
      'Full security system',
    ],
    photos: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: {
      name: 'Michael Hargrove',
      title: "Co-Founder · Buyer's Specialist",
      phone: '(713) 555-0183',
      email: 'michael@hargrovegroup.com',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
      license: 'TX Lic# 0618742',
    },
    coordinates: { lat: 29.7991, lng: -95.4057 },
  },
  {
    slug: '5510-fairdale-ln',
    address: '5510 Fairdale Ln',
    neighborhood: 'Galleria',
    city: 'Houston, TX 77056',
    listPrice: '$598,000',
    beds: 3,
    baths: 2,
    sqft: '1,740',
    lotSize: 'N/A (Condo)',
    yearBuilt: 2018,
    type: 'Condo',
    status: 'Under Contract',
    description: [
      'A sophisticated Galleria-area condo offering three bedrooms, two baths, and a private terrace with views of the Galleria skyline. Located in a boutique mid-rise building, this unit features an open-concept living area, floor-to-ceiling windows, and high-end finishes throughout.',
      'The kitchen features Bosch appliances, quartz counters, and a large island with seating. The primary suite includes custom closet systems, a spa-quality bath with heated floors, and direct terrace access. Building amenities include a rooftop pool, fitness center, and 24-hour concierge.',
    ],
    features: [
      'Private terrace with Galleria skyline views',
      'Floor-to-ceiling windows',
      'Bosch appliance package',
      'Heated bathroom floors in primary suite',
      'Custom closet systems',
      'Two assigned parking spaces',
      'Storage unit included',
      'Pet-friendly building',
    ],
    amenities: [
      'Rooftop pool and lounge',
      'Fitness center',
      '24-hour concierge',
      'Guest parking',
      'Package lockers',
      'EV charging stations',
    ],
    photos: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: {
      name: 'Jessica Chen',
      title: "Senior Buyer's Agent · Relocation Specialist",
      phone: '(713) 555-0184',
      email: 'jessica@hargrovegroup.com',
      photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80',
      license: 'TX Lic# 0703819',
    },
    coordinates: { lat: 29.7370, lng: -95.4614 },
  },
  {
    slug: '22-greenbay-st',
    address: '22 Greenbay St',
    neighborhood: 'Memorial',
    city: 'Houston, TX 77024',
    listPrice: '$2,250,000',
    beds: 5,
    baths: 6,
    sqft: '5,920',
    lotSize: '14,000 sf',
    yearBuilt: 2020,
    type: 'Single Family',
    status: 'For Sale',
    description: [
      'An extraordinary Memorial estate on a 14,000 sf lot, offering five bedrooms, six baths, a resort-style pool, and a four-car garage. Built in 2020 to exacting standards, this home was designed by a prominent Houston architect and features hand-selected natural materials throughout.',
      'The ground floor is anchored by a dramatic two-story entry, formal living and dining rooms, a professional-grade kitchen, and a glass-walled family room that opens fully to the outdoor living space. The backyard features a negative-edge pool, covered loggia, full outdoor kitchen, and lush landscaping designed for complete privacy.',
    ],
    features: [
      'Negative-edge pool with spa',
      'Full outdoor kitchen and covered loggia',
      'Professional-grade kitchen with La Cornue range',
      'Two-story entry with custom iron staircase',
      'Wine cellar (300+ bottles)',
      'Home theater with tiered seating',
      'Four-car garage with finished floors',
      'Whole-home Crestron automation system',
    ],
    amenities: [
      'Home theater',
      'Wine cellar',
      'Exercise room',
      'Game room',
      'Formal study',
      'Secondary laundry on second floor',
    ],
    photos: [
      'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: {
      name: 'Sarah Hargrove',
      title: 'Team Lead · Listing Specialist',
      phone: '(713) 555-0182',
      email: 'sarah@hargrovegroup.com',
      photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80',
      license: 'TX Lic# 0624531',
    },
    coordinates: { lat: 29.7659, lng: -95.4808 },
  },
  {
    slug: '3703-inker-st',
    address: '3703 Inker St',
    neighborhood: 'Rice Military',
    city: 'Houston, TX 77007',
    listPrice: '$679,000',
    beds: 3,
    baths: 3,
    sqft: '2,150',
    lotSize: '2,200 sf',
    yearBuilt: 2022,
    type: 'Townhome',
    status: 'For Sale',
    description: [
      'A 2022-built Rice Military townhome offering three bedrooms, three full baths, and a rooftop deck just minutes from Memorial Park and the Washington Avenue corridor. Clean, modern design with premium finishes and a low-maintenance lifestyle in one of Houston\'s most active Inner Loop neighborhoods.',
      'The kitchen features Jenn-Air appliances, Calacatta marble counters, and custom European cabinetry. The primary suite includes a spa bath with double rainfall shower and a large custom closet. The fourth-floor rooftop deck provides skyline views and ample space for outdoor entertaining.',
    ],
    features: [
      'Rooftop deck with downtown skyline views',
      'Jenn-Air appliance package',
      'Calacatta marble kitchen counters',
      'European custom cabinetry',
      'Double rainfall shower in primary bath',
      'Private two-car garage',
      'Energy-efficient spray foam insulation',
      'Walking distance to Memorial Park',
    ],
    amenities: [
      'Rooftop deck',
      'Private 2-car garage',
      'Custom closet system',
      'Tankless water heater',
      'Smart home features',
      'Pre-wired for EV charger',
    ],
    photos: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    agent: {
      name: 'Michael Hargrove',
      title: "Co-Founder · Buyer's Specialist",
      phone: '(713) 555-0183',
      email: 'michael@hargrovegroup.com',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80',
      license: 'TX Lic# 0618742',
    },
    coordinates: { lat: 29.7652, lng: -95.4101 },
  },
]
